### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by brustmopf** [sswelm/KSP-Interstellar-Extended#19]
Hi,

There are some textures referenced by the part models which are not in their folder. Would it be possible to add  them to the repo or remove the reference from the model ? 
If you wish I can do the removal myself if provided with the original model files...

I tried to make you a (hopefully exhaustive list here) with the convention Modelname->Missing texture parth:

- qvengine2.mu
-> WarpPlugin/Parts/Engines/PlasmaWakefieldAccelerator/IXS_ENGINE_emissive

- resourcesphere.mu
-> WarpPlugin/PlasmaMedGlow

- interstellarAmmoniaExhaust.mu, interstellarArgonExhaust.mu,interstellarChargedExhaust.mu, interstellarHydrogenExhaust.mu, interstellarLithiumExhaust.mu, interstellarQVPExhaust.mu, interstellarXenonExhaust.mu
-> WarpPlugin/FX/puff

- LANTR_small.mu, NTR_mini.mu, NTR_small.mu
-> WarpPlugin/FX/plasma

- ixsmainhull.mu
-> WarpPlugin/Parts/Electrical/IXSMainHull/ixs_MAINHULL_EMISSIVE_tga

- warpring.mu
-> WarpPlugin/Parts/Electrical/IXSWarpRing/ixs_WARPING_EMISSIVE_finalTGA

- mhdg.mu
->WarpPlugin/Parts/Electrical/MHDGenerator/big_diff

-WarpPlugin/Parts/Engines/RCSTank/model.mu
-> WarpPlugin/Parts/Engines/RCSTank/cstSolar

- WrapperTank.mu 
-> WarpPlugin/Parts/FuelTank/WrapperTank/Decoupler

-WarpPlugin/Parts/Microwave/RadialThermalReceiverDishAluminium/model.mu
->WarpPlugin/Parts/Microwave/RadialThermalReceiverDishAluminium/ORI69

**Comment by arivaldh** [comment]
I have searched log files by:
"Cannot replace texture"
"Cannot clone model"
Texture '*' not found!

I have fixed two first issues.

I have found missing textures:
[LOG 22:41:21.872] Load(Model): InterstellarFuelSwitch/Parts/TankRevamp/modelCDTcore
[ERR 22:41:21.881] Texture 'InterstellarFuelSwitch/Parts/TankRevamp/iHAL' not found!
[ERR 22:41:21.883] Texture 'InterstellarFuelSwitch/Parts/TankRevamp/iHAL_NRM' not found!
[ERR 22:41:21.884] Texture 'InterstellarFuelSwitch/Parts/TankRevamp/iHAL_EMM' not found!

[LOG 22:41:32.576] Load(Model): WarpPlugin/Parts/Engines/PlasmaWakefieldAccelerator/qvengine2
[ERR 22:41:32.584] Texture 'WarpPlugin/Parts/Engines/PlasmaWakefieldAccelerator/IXS_ENGINE_emissive' not found!

[LOG 22:41:32.588] Load(Model): WarpPlugin/Parts/Engines/RCSTank/model
[ERR 22:41:32.656] Texture 'WarpPlugin/Parts/Engines/RCSTank/cstSolar' not found!

[LOG 22:41:37.210] Load(Model): WarpPlugin/Parts/Science/scienceDrill/model
[ERR 22:41:37.222] Texture 'WarpPlugin/Parts/Science/scienceDrill/nrm_NRM' not found!

So a lot less than sometime ago. But still there are some.

**Comment by arivaldh** [comment]
@sswelm  I will need your assistance here.

**Comment by sswelm** [comment]
seems to me he hasn't installed IFS, that the only way I can think of he got these messages

**Comment by sswelm** [comment]
I think modelCDTcore.mu can be remove, it is moved from TankRevamp, it is moved to WarpPlugin\Parts\Command\iHall

**Comment by sswelm** [comment]
found IXS_ENGINE_emissive.tga from the original mod

**Comment by sswelm** [comment]
also found nrm_NRM.tga

**Comment by sswelm** [comment]
also found cstSolar

**Comment by EleusisLaArwall** [comment]
modelCDTcore.mu is redundant and can be removed from IFS. Now located in WarpPlugin.

The other three are actually missing textures.
I can make some placeholder-textures to remove the warnings if the originals can't be found anymore.

**Comment by arivaldh** [comment]
I have took KSP from sswelm:master to verify if the problem was fixed. Yes, and no.
New missing textures:
[LOG 22:41:12.930] Load(Model): WarpPlugin/FX/fx-sc-lh2-125-core
[ERR 22:41:12.932] Texture 'WarpPlugin/FX/fx_blob02' not found!

[LOG 22:41:12.935] Load(Model): WarpPlugin/FX/fx-sc-lh2-125-plume
[ERR 22:41:12.937] Texture 'WarpPlugin/FX/fx_blob02' not found!

[LOG 22:41:12.940] Load(Model): WarpPlugin/FX/fx-sc-lox-125-core
[ERR 22:41:12.941] Texture 'WarpPlugin/FX/fx_firey01' not found!

[LOG 22:41:12.944] Load(Model): WarpPlugin/FX/fx-sc-lox-125-plume
[ERR 22:41:12.946] Texture 'WarpPlugin/FX/fx_firey01' not found!

[LOG 22:41:13.249] Load(Model): WarpPlugin/Parts/Electrical/MuonCatFusionReactor2/StnSciSpectro
[ERR 22:41:13.274] Texture 'WarpPlugin/Parts/Electrical/MuonCatFusionReactor2/NewLab' not found!

[ERR 22:41:13.275] Texture 'WarpPlugin/Parts/Electrical/MuonCatFusionReactor2/NewLabN' not found!

[ERR 22:41:13.276] Texture 'WarpPlugin/Parts/Electrical/MuonCatFusionReactor2/NewLabEm' not found!

[LOG 22:41:18.483] Load(Model): WarpPlugin/Parts/Utility/Cyclotron/StnSciCyclo
[ERR 22:41:18.515] Texture 'WarpPlugin/Parts/Utility/Cyclotron/NewLab' not found!

[ERR 22:41:18.516] Texture 'WarpPlugin/Parts/Utility/Cyclotron/NewLabN' not found!

[ERR 22:41:18.517] Texture 'WarpPlugin/Parts/Utility/Cyclotron/NewLabEm' not found!

Last two batches seems to be a name changes.

**Comment by arivaldh** [comment]
Two batches are fixed.
[LOG 23:18:10.397] Load(Model): WarpPlugin/FX/fx-sc-lh2-125-core
is still present.

New problem:
[ERR 23:21:17.965] PartCompiler: Cannot replace texture 'CircularPanel2001' as cannot find texture 'WarpPlugin/Parts/BeamedPower/Thermophotovoltaic/CircularThermophotovoltaicReceiver/CircularPanel2001' to replace with

**Comment by sswelm** [comment]
should be fixed now

**Comment by arivaldh** [comment]
Just checked. It's fixed.
We would need some automatic inspection tool in order to find those problems automatically in the future.

**Comment by sswelm** [comment]
Structural inspection of the logs after major changes should be enough for now. Well done!
