### ISSUE TITLE
Game gets stuck on startup at "Loading PartRecipe for KSPIE-VASIMR2"

### ISSUE THREAD

**Issue by mr-engino** [sswelm/KSP-Interstellar-Extended#208]
Dunno what went wrong, but the game was working fine yesterday.

**Comment by sswelm** [comment]
I heard this bug is related to OSE workshop which not KSP 1,4.x compatible

**Comment by maranble14** [comment]
I had this issue without any OSE files installed.

**Comment by Kiithnaras** [comment]
Actually, I have found a resolution, and it is all KSPIE's fault:
Within the deprecated \Parts\Microwave folder is a singular part config (InlineSolarReceiverPanel) with the text "PART{}". All other config files within \Microwave are completely blank. Deleting the entire \Microwave folder (to be safe, rather than just the single part file in question) resolved the OSE Workshop loading issue, as the recipe generator was attempting to create a recipe for a part with no attributes and likely causing the exhibited nullref within its script:

> [EXC 04:08:47.066] NullReferenceException: Object reference not set to an instance of an object
> Workshop.Recipes.WorkshopRecipeLoader+d__4.MoveNext ()
> UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)

Loading for OSE Workshop experienced no issues without WarpPlugin installed, and the issue did not resolve by simply deleting the parts that appeared to cause the issue, even up to appearing to hang on a USI MKS part which, when WarpPlugin was absent, did not cause this issue.

It was merely a leap of intuition that led me to the \Microwave folder, as I had previously done some editing of some phased array parts and had prior knowledge of this folder with its empty configs.

**Comment by Kiithnaras** [comment]
https://github.com/Aelfhe1m/Workshop/issues/8

**Comment by sswelm** [comment]
The \Parts\Microwave was already deleted from KSPIE folder structure, so it this still relevant?

**Comment by Kiithnaras** [comment]
Testing the most recent version of WarpPlugin, things load perfectly fine, so this is only relevant to players running older versions of KSPIE in terms of workarounds without updating.

(Now to go re-tweak things because I accidentally deleted my previous copy of WarpPlugin. *grumble*)
