### ISSUE TITLE
KSPIE 1.19.4; KSP 1.4.5 Closed Cycle Gas Engine causes ship delete on scene change

### ISSUE THREAD

**Issue by Uberns** [sswelm/KSP-Interstellar-Extended#238]
KSPIE 1.19.4 and KSP 1.4.5.
Mods installed - KSPIE (and packaged mods), karbonite/karbonite+, hyperedit.

A ship with an **ACTIVATED** Closed Cycle Gas Engine will be deleted from the game when you scene change to it.  

Steps to reproduce: 
1. Make a ship with probe core, LH2 tank, batteries, radiators, and a Closed Cycle Gas Engine.
2. Launch it or hyper edit it into orbit
3. activate the engine
4. Switch to the space center
5. Switch back to the ship
6.  Observe the ship load momentarily and then vanish before/when physics kick in.  The height indicator changes to 00000 and the speed indicator changes to NAN.  See this image  [https://i.imgur.com/ybn4bDA.png](https://i.imgur.com/ybn4bDA.png)

Activating the engine is a must.  If the engine is not activated, the ship will load like normal.  Also, activating and then deactivating the engine will still cause the ship to vanish.  I also tried using methane instead of LH2 and tried switching fuels after activating.  Activating the engine appears to be the crucial step.

Also, it will not happen when the rocket is still on the launch pad.

**Comment by Sn0wStorm** [comment]
The same issue appears using the Magnetic Nozzle or Plasma Nozzle with any Reactor. Switching to the Ship in orbit after the engine has been activated once will delete the ship.
The issue seems to be that these engines support Warp Thrust.

Editing` GameData/Parts/Engines/MagneticNozzle2/MagneticNozzle2.cfg` replacing `ModuleEnginesWarp` with `ModuleEnginesFX` fixes the issue for the Plasma Nozzle (edit MagneticNozzle3 for the Magnetic Nozzle)
As far as I can see this only removes the Warp Thrust capability but switching to the ship works again.

**Comment by sswelm** [comment]
For 1.19.5 I have replaced ModuleEnginesWarp  with ModuleEnginesFX, later I intend to restore it back once I have fixed the divide by zerro problem in ModuleEnginesWarp

**Comment by sswelm** [comment]
Problem is found and fixed in KSPIE 1.19.8
