### ISSUE TITLE
RFC2501 tank UF6 and UF4 confusion

### ISSUE THREAD

**Issue by superdavekerman** [sswelm/KSP-Interstellar-Extended#36]
I noticed some mismatch between UF4 and UF6 in the VAB while configuring the tank. Looking at the source file, UF6 and Uraniumhexaflouride are used on lines 74,75,86 but the resource name used on the following line in position 3 is UF4. Since the reactors all seem to need UF4 I'm guessing this is a cosmetic bug only.

**Comment by arivaldh** [comment]
I'll check this issue.

**Comment by arivaldh** [comment]
Ok. @sswelm : 
RFC2500/2501/2502 tanks are defined by FuelSwitch. Their mesh and switchables are also defined in FS.
RFC2501 is also defined in KSPI-E. Also with switchables.
Should I:
1) remove RFC2501 totally from KSPI-E and fix names in FuelSwitch.
2) remove RFC2501 switchables from KSPI-E and fix names in FuelSwitch.
3) keep RFC2501, fix switchables in both KSPI-E and FuelSwitch.
4) keep RFC2501 but remove switchables from KSPI-E and keep FuelSwitch.

I'd happily do 1) but since Interstellar Fuel Switch is only recommended, then I believe 3) should be the preffered choice.

**Comment by arivaldh** [comment]
Option 3) implemented in:
https://github.com/arivaldh/KSP-Interstellar-Extended/commit/6a31631424bbbef39e65e334aa3fd2c425d32375
Removed "switcherDescription = Tank" from RFC2501 in KSPI-E since it should be localized (and will probably be overwritten by MM changes in FS)
Also please notice that regardless of this change "basePartMass = 2" will be overwritten to 1.5 by FS changes.

**Comment by sswelm** [comment]
Option 3 is good

**Comment by arivaldh** [comment]
Please close after verification.
