### ISSUE TITLE
Problem with fuel types for thermal turbo jet and ramjet

### ISSUE THREAD

**Issue by serp777** [sswelm/KSP-Interstellar-Extended#664]
Hello,

Currently the thermal turbojet and ramjet don't let you use LH2 or liquid fuel, but they do let you use LH4, liquid CO2, etc? AM I doing something wrong here? The crusader doesn't seem to have this problem. See below for the selection of fuels that I have access to for the ramjet. I am using the latest build. Thanks for your input.

![image](https://user-images.githubusercontent.com/10540204/102744058-b5e12880-430d-11eb-86a6-7b77492dff3a.png)

**Comment by sswelm** [comment]
this is intended. At high temperatures, propellants andheat exhanger become reactive. To prevent this, an coating is used. However, the coating can only be anti redusing or anti oxidising. In order to function in an oxigen rich atmosphere, it need to use an anti oxidising coating, As a consequence, it cannot use any reducing propellants lik hydrogen.

**Comment by serp777** [comment]
> this is intended. At high temperatures, propellants and heat exchanger become reactive. To prevent this, a coating is used. However, the coating can only be anti reducing or anti-oxidizing. In order to function in an oxygen-rich atmosphere, it need to use an anti-oxidizing coating, As a consequence, it cannot use any reducing propellants like hydrogen.

thanks that makes sense.
