### ISSUE TITLE
Charged particle direct power converter cant find the Tri Alpha fusionr reactor 

### ISSUE THREAD

**Issue by alismatales** [sswelm/KSP-Interstellar-Extended#82]
I tracked it down to the line 

>                          && p.ConnectedChargedParticleElectricGenerator == null
 
in FNGenerators.cs line 569 which is not null in this instance, even though it should be. 

I suspect it has something to do with the built-in generator of the tri alpha reactor.

**Comment by sswelm** [comment]
Did you know the Tri Alpha fusion reactor has a build in charged particle reactor, that mean any external charged particle generator connected to it will not be able to provide any power

**Comment by alismatales** [comment]
Aw, geez, hours of sourcecode digging for a little mixup. Hah. 

I thought it had an integrated thermal generator and needed an external charged particle generator.. not vice versa.

**Comment by sswelm** [comment]
Well technically the fusion chamber is surrounded by an X-ray receiver which is neither thermal thermal nor charged particles, but because of it potential high efficiency of 90%, I count it as Charged particle power. This is also the reason why you cannot use it for any propulsion, because a large part of the energy would not be in the form of charged particles but high energy photons
